<?php

namespace App\Services;

use App\Models\Account;
use App\Models\EmailFilter;
use App\Models\EmailFilterCondition;
use App\Models\EmailFilterAction;
use Illuminate\Support\Facades\File;

class SieveScriptGenerator
{
    /**
     * Generate Sieve script for an email address
     */
    public function generate(Account $account, string $email): string
    {
        $filters = EmailFilter::where('account_id', $account->id)
            ->where('email', $email)
            ->where('is_active', true)
            ->with(['conditions', 'actions'])
            ->byPriority()
            ->get();

        if ($filters->isEmpty()) {
            return $this->generateEmptyScript();
        }

        $script = $this->generateHeader();

        foreach ($filters as $filter) {
            $script .= $this->generateFilterRule($filter);
        }

        $script .= $this->generateFooter();

        return $script;
    }

    /**
     * Generate header for Sieve script
     */
    private function generateHeader(): string
    {
        return "# VirPanel Generated Sieve Filter Rules\n" .
               "# DO NOT EDIT THIS FILE MANUALLY\n" .
               "# Managed by VirPanel Email Filters\n" .
               "# Generated: " . date('Y-m-d H:i:s') . "\n\n" .
               "require [\"fileinto\", \"reject\", \"vacation\", \"envelope\", \"body\", \"relational\", \"comparator-i;ascii-numeric\"];\n\n";
    }

    /**
     * Generate footer for Sieve script
     */
    private function generateFooter(): string
    {
        return "\n# End of VirPanel filters\n";
    }

    /**
     * Generate empty script
     */
    private function generateEmptyScript(): string
    {
        return "# VirPanel Generated Sieve Filter Rules\n" .
               "# No active filters configured\n" .
               "# Generated: " . date('Y-m-d H:i:s') . "\n";
    }

    /**
     * Generate a single filter rule
     */
    private function generateFilterRule(EmailFilter $filter): string
    {
        $script = "# Filter: {$filter->name}\n";

        if ($filter->description) {
            $script .= "# Description: {$filter->description}\n";
        }

        $script .= "# Priority: {$filter->priority}\n";

        // Check for vacation action (special handling)
        $vacationAction = $filter->actions->firstWhere('action_type', 'vacation');
        if ($vacationAction) {
            return $this->generateVacationRule($filter, $vacationAction);
        }

        // Generate conditions
        if ($filter->conditions->isEmpty()) {
            // No conditions means match all
            $script .= "if true {\n";
        } else {
            $script .= $this->generateConditions($filter);
        }

        // Generate actions
        $script .= $this->generateActions($filter);

        $script .= "}\n\n";

        return $script;
    }

    /**
     * Generate conditions for a filter
     */
    private function generateConditions(EmailFilter $filter): string
    {
        $matchType = $filter->matchesAll() ? 'allof' : 'anyof';
        $conditions = [];

        foreach ($filter->conditions as $condition) {
            $conditions[] = $this->generateCondition($condition);
        }

        if (count($conditions) === 1) {
            return "if " . $conditions[0] . " {\n";
        }

        return "if {$matchType} (\n  " . implode(",\n  ", $conditions) . "\n) {\n";
    }

    /**
     * Generate a single condition
     */
    private function generateCondition(EmailFilterCondition $condition): string
    {
        $field = $this->mapFieldToSieve($condition->field, $condition->header_name);
        $operator = $this->mapOperatorToSieve($condition->operator);
        $value = $this->escapeValue($condition->value);
        $comparator = $condition->case_sensitive ? '' : ':comparator "i;ascii-casemap" ';

        // Handle size comparisons
        if ($condition->field === 'size') {
            $sizeBytes = intval($condition->value) * 1024; // Convert KB to bytes
            $operator = $condition->operator === 'greater_than' ? ':over' : ':under';
            return "size {$operator} {$sizeBytes}";
        }

        // Handle numeric comparisons
        if (in_array($condition->operator, ['greater_than', 'less_than'])) {
            $comparator = ':comparator "i;ascii-numeric" ';
            if ($condition->operator === 'greater_than') {
                $operator = ':value "gt"';
            } else {
                $operator = ':value "lt"';
            }
        }

        // Handle regex
        if ($condition->operator === 'matches_regex') {
            $operator = ':regex';
        }

        return "{$field} {$comparator}{$operator} \"{$value}\"";
    }

    /**
     * Map database field to Sieve field
     */
    private function mapFieldToSieve(string $field, ?string $headerName = null): string
    {
        return match ($field) {
            'from' => 'header "From"',
            'to' => 'header "To"',
            'subject' => 'header "Subject"',
            'body' => 'body :text',
            'sender' => 'envelope "from"',
            'recipient' => 'envelope "to"',
            'header' => $headerName ? "header \"{$headerName}\"" : 'header "X-Custom"',
            'spam_score' => 'header "X-Spam-Score"',
            default => 'header "Subject"',
        };
    }

    /**
     * Map database operator to Sieve operator
     */
    private function mapOperatorToSieve(string $operator): string
    {
        return match ($operator) {
            'contains' => ':contains',
            'not_contains' => ':contains', // Will be negated with 'not'
            'equals' => ':is',
            'not_equals' => ':is', // Will be negated with 'not'
            'begins_with' => ':matches',
            'ends_with' => ':matches',
            'matches_regex' => ':regex',
            'greater_than' => ':value "gt"',
            'less_than' => ':value "lt"',
            default => ':contains',
        };
    }

    /**
     * Generate actions for a filter
     */
    private function generateActions(EmailFilter $filter): string
    {
        $script = "";

        foreach ($filter->actions as $action) {
            $script .= "  " . $this->generateAction($action) . "\n";
        }

        return $script;
    }

    /**
     * Generate a single action
     */
    private function generateAction(EmailFilterAction $action): string
    {
        return match ($action->action_type) {
            'move_to_folder' => "fileinto \"{$this->escapeValue($action->action_value)}\";",
            'forward' => "redirect \"{$this->escapeValue($action->action_value)}\";",
            'redirect' => "redirect \"{$this->escapeValue($action->action_value)}\";\n  discard;",
            'delete' => "discard;",
            'reject' => "reject \"{$this->escapeValue($action->action_value)}\";",
            'discard' => "discard;",
            'mark_as_read' => "# Mark as read (requires imap4flags extension)\n  addflag \"\\\\Seen\";",
            'flag' => "# Flag message (requires imap4flags extension)\n  addflag \"\\\\Flagged\";",
            'pipe_to_program' => "# Pipe to program: {$action->action_value}",
            'stop' => "stop;",
            default => "# Unknown action: {$action->action_type}",
        };
    }

    /**
     * Generate vacation rule
     */
    private function generateVacationRule(EmailFilter $filter, EmailFilterAction $action): string
    {
        $script = "# Vacation Auto-Reply: {$filter->name}\n";
        $script .= "# Status: " . ($filter->is_active ? 'Active' : 'Inactive') . "\n\n";

        if (!$filter->is_active) {
            $script .= "# Vacation responder is currently disabled\n\n";
            return $script;
        }

        $days = $action->vacation_days ?? 7;
        $subject = $this->escapeValue($action->vacation_subject);
        $message = $this->escapeValue($action->vacation_message);

        $script .= "vacation\n";
        $script .= "  :days {$days}\n";
        $script .= "  :subject \"{$subject}\"\n";
        $script .= "  \"{$message}\";\n\n";

        return $script;
    }

    /**
     * Escape value for Sieve script
     */
    private function escapeValue(string $value): string
    {
        return addslashes($value);
    }

    /**
     * Save Sieve script to file
     */
    public function save(Account $account, string $email, string $script): void
    {
        $baseDir = "/var/vmail/sieve/" . $account->username;

        // Create directory if not exists
        if (!File::isDirectory($baseDir)) {
            File::makeDirectory($baseDir, 0755, true);
        }

        // Generate filename
        $emailPart = str_replace('@', '_at_', $email);
        $filename = "{$baseDir}/{$emailPart}.sieve";

        // Write script to file
        File::put($filename, $script);

        // Set permissions
        chmod($filename, 0644);

        // Compile Sieve script (using sievec if available)
        $this->compileSieve($filename);
    }

    /**
     * Compile Sieve script to bytecode
     */
    private function compileSieve(string $filename): void
    {
        // Check if sievec is available
        if (file_exists('/usr/bin/sievec')) {
            $output = shell_exec("/usr/bin/sievec \"{$filename}\" 2>&1");

            // Log any compilation errors
            if ($output && strpos($output, 'error') !== false) {
                \Log::error("Sieve compilation error: {$output}");
            }
        }
    }

    /**
     * Import Sieve script and convert to database filters
     */
    public function import(Account $account, string $email, string $script): int
    {
        // This is a basic implementation
        // A full parser would be more complex and handle all Sieve syntax

        $imported = 0;
        $lines = explode("\n", $script);
        $currentFilter = null;
        $priority = 100;

        foreach ($lines as $line) {
            $line = trim($line);

            // Skip comments and empty lines
            if (empty($line) || str_starts_with($line, '#')) {
                continue;
            }

            // Parse vacation command
            if (str_starts_with($line, 'vacation')) {
                $filter = EmailFilter::create([
                    'account_id' => $account->id,
                    'email' => $email,
                    'name' => 'Imported Vacation Responder',
                    'priority' => $priority++,
                    'is_active' => true,
                    'match_type' => 'all',
                ]);

                // Parse vacation parameters (basic implementation)
                preg_match('/:days\s+(\d+)/', $script, $days);
                preg_match('/:subject\s+"([^"]+)"/', $script, $subject);
                preg_match('/vacation.*"([^"]+)"\s*;/s', $script, $message);

                EmailFilterAction::create([
                    'filter_id' => $filter->id,
                    'action_type' => 'vacation',
                    'vacation_days' => $days[1] ?? 7,
                    'vacation_subject' => $subject[1] ?? 'Vacation Reply',
                    'vacation_message' => $message[1] ?? 'I am currently out of office.',
                    'order' => 1,
                ]);

                $imported++;
            }

            // Additional parsing logic would go here for other filter types
        }

        return $imported;
    }

    /**
     * Validate Sieve script syntax
     */
    public function validate(string $script): array
    {
        $errors = [];

        // Basic validation
        if (empty($script)) {
            $errors[] = 'Script cannot be empty';
        }

        // Check for required extensions if they're used
        if (str_contains($script, 'fileinto') && !str_contains($script, 'require ["fileinto"')) {
            $errors[] = 'Script uses fileinto but does not require the extension';
        }

        if (str_contains($script, 'vacation') && !str_contains($script, 'require ["vacation"')) {
            $errors[] = 'Script uses vacation but does not require the extension';
        }

        // Check for balanced braces
        $openBraces = substr_count($script, '{');
        $closeBraces = substr_count($script, '}');

        if ($openBraces !== $closeBraces) {
            $errors[] = 'Unbalanced braces in script';
        }

        return $errors;
    }
}
